[package]
name = "remote_cli"
version = "0.1.0"
edition = "2021"

[dependencies]
dotenvy = "0.15.7"
clap = { version = "4.4.7", features = ["derive"] }
remote_core = { path = "../remote_core/" }
chrono = {version = "0.4.31", features = ["serde"] }
