[package]
name = "remote_core"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = {version = "0.4.31", features = ["serde"] }
serde = { version = "1.0.192", features = ["derive"] }
serde_json = "1.0.108"
dotenvy = "0.15.7"
